---
name: xcop
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  xcop:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: g4s8/xcop-action@master